baseURL = '/'
languageCode = 'ru-ru'
title = 'Synthadry'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  defaultTheme = "light"
  publishDir = "../docs"
  homeInfoParams = { Title = "Synthadry", Content = "Это главная страница проекта. Здесь будет аннотация проекта." }
  ShowPostsOnHomePage = false


[[menu.main]]
name = "О проекте"
url = "/about"
weight = 1

[[menu.main]]
name = "Участники"
url = "/participants"
weight = 2

[[menu.main]]
name = "Журнал"
url = "/journal"
weight = 3

[[menu.main]]
name = "Ресурсы"
url = "/resources"
weight = 4

